# Generated by Django 4.2.29 on 2026-03-19 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(editable=False, max_length=10, unique=True)),
                ('ticket_type', models.CharField(choices=[('FLIGHT', 'Flight'), ('TRAIN', 'Train'), ('BUS', 'Bus')], max_length=10)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('WAITING', 'Waiting List'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('journey_date', models.DateField()),
                ('journey_time', models.TimeField()),
                ('passenger_name', models.CharField(max_length=200)),
                ('passenger_age', models.IntegerField()),
                ('passenger_gender', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.ticket')),
                ('bus_operator', models.CharField(max_length=100)),
                ('bus_number', models.CharField(max_length=20)),
                ('bus_type', models.CharField(max_length=50)),
                ('boarding_point', models.CharField(max_length=100)),
                ('dropping_point', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration', models.CharField(max_length=20)),
                ('seat_numbers', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tickets_bus',
            },
            bases=('tickets.ticket',),
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.ticket')),
                ('airline_name', models.CharField(max_length=100)),
                ('flight_number', models.CharField(max_length=20)),
                ('departure_airport', models.CharField(max_length=100)),
                ('arrival_airport', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration', models.CharField(max_length=20)),
                ('seat_class', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tickets_flight',
            },
            bases=('tickets.ticket',),
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.ticket')),
                ('train_name', models.CharField(max_length=100)),
                ('train_number', models.CharField(max_length=20)),
                ('boarding_station', models.CharField(max_length=100)),
                ('arrival_station', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration', models.CharField(max_length=20)),
                ('coach', models.CharField(max_length=20)),
                ('seat_number', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'tickets_train',
            },
            bases=('tickets.ticket',),
        ),
    ]
