# Generated by Django 5.2.7 on 2026-03-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_operator', models.CharField(max_length=100)),
                ('bus_number', models.CharField(max_length=20, unique=True)),
                ('bus_type', models.CharField(choices=[('AC_SEATER', 'AC Seater'), ('NON_AC_SEATER', 'Non-AC Seater'), ('AC_SLEEPER', 'AC Sleeper'), ('NON_AC_SLEEPER', 'Non-AC Sleeper'), ('VOLVO', 'Volvo'), ('SCANIA', 'Scania')], max_length=20)),
                ('boarding_point', models.CharField(max_length=100)),
                ('dropping_point', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration', models.CharField(max_length=20)),
                ('journey_date', models.DateField()),
                ('total_seats', models.PositiveIntegerField(default=40)),
                ('available_seats', models.PositiveIntegerField(default=40)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_cancelled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['departure_time', 'journey_date'],
            },
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=100)),
                ('flight_number', models.CharField(max_length=20, unique=True)),
                ('departure_airport', models.CharField(max_length=100)),
                ('arrival_airport', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration', models.CharField(max_length=20)),
                ('journey_date', models.DateField()),
                ('seat_class', models.CharField(choices=[('ECONOMY', 'Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First Class')], max_length=20)),
                ('airline_type', models.CharField(choices=[('DOMESTIC', 'Domestic'), ('INTERNATIONAL', 'International')], default='DOMESTIC', max_length=20)),
                ('total_seats', models.PositiveIntegerField(default=100)),
                ('available_seats', models.PositiveIntegerField(default=100)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_cancelled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['departure_time', 'journey_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=20, unique=True)),
                ('train_name', models.CharField(max_length=100)),
                ('train_type', models.CharField(choices=[('EXPRESS', 'Express'), ('SUPERFAST', 'Superfast'), ('PASSENGER', 'Passenger'), ('RAJDHANI', 'Rajdhani'), ('SHATABDI', 'Shatabdi'), ('DURONTO', 'Duronto')], max_length=20)),
                ('source_station', models.CharField(max_length=100)),
                ('destination_station', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration', models.CharField(max_length=20)),
                ('journey_date', models.DateField()),
                ('coach_class', models.CharField(choices=[('SL', 'Sleeper'), ('3A', 'AC 3 Tier'), ('2A', 'AC 2 Tier'), ('1A', 'AC First Class'), ('CC', 'Chair Car'), ('2S', 'Second Sitting')], max_length=10)),
                ('total_seats', models.PositiveIntegerField(default=72)),
                ('available_seats', models.PositiveIntegerField(default=72)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_cancelled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['departure_time', 'journey_date'],
            },
        ),
    ]
